#!/bin/sh

heroku config:set STG_CONSUMERKEY=$STG_CONSUMERKEY
heroku config:set STG_CONSUMERSECRET=$STG_CONSUMERSECRET
heroku config:set PROD_CONSUMERKEY=$ROOMEDIT3D_PROD_CONSUMER_KEY
heroku config:set PROD_CONSUMERSECRET=$ROOMEDIT3D_PROD_CONSUMER_SECRET
heroku config:set CALLBACK_URL=$ROOMEDIT3D_PROD_CALLBACK_URL
